# Generated by Django 3.1.5 on 2021-01-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('name', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('coords', models.JSONField()),
                ('weather', models.JSONField()),
                ('travel', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.TextField(max_length=10)),
                ('duration', models.DurationField()),
                ('url', models.TextField(max_length=50)),
                ('end_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.node')),
                ('start_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.node')),
            ],
        ),
    ]
