# Generated by Django 3.1.5 on 2021-01-26 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='id',
        ),
        migrations.AddField(
            model_name='edge',
            name='route_id',
            field=models.TextField(default=django.utils.timezone.now, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
