# Generated by Django 3.1.5 on 2021-01-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210126_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='end_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='edge',
            name='start_name',
            field=models.TextField(max_length=50),
        ),
    ]
